version: "3.7"

services:
  webclient:
    build: ./webclient
    restart: always
    ports:
      - 8080:80

  webserver:
    build: 
      context: ./webserver
      args:
        - SPRING_DATASOURCE_URL="jdbc:mysql://mysql:3306/shopping_list"
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - mysql
    command: sh -c './webserver/wait-for mysql:3306 -- npm start'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shopping_list

  mysql:
    image: "mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: shopping_list
      MYSQL_USER: webserveruser
      MYSQL_PASSWORD: geheim
      MYSQL_ROOT_PASSWORD: geheim