version: "3.7"

services:
  mysql:
    image: "mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: shopping_list
      MYSQL_USER: webserveruser
      MYSQL_PASSWORD: geheim
      MYSQL_ROOT_PASSWORD: geheim